# Basic
max_width = 160
attr_fn_like_width = 160
#indent_style = "Block"

# Imports
merge_derives = false
imports_granularity="Crate"
group_imports = "StdExternalCrate"

# Misc
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
use_field_init_shorthand = false