[source.crates-io]
replace-with = 'rsproxy'
[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"
[source.tsinghua]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

#[build]
#jobs = 10
#rustflags = ["-C", "target-cpu=native"]


